app/models.py
from app import db, login
from passlib.hash import pbkdf2_sha256 as pwd_context
from flask_login import UserMixin
from hashlib import md5


# TODO: Test
@login.user_loader
def load_user(user_id):
    return User.query.get(user_id)


tried = db.Table('tried',
                 db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                 db.Column('strain_id', db.Integer, db.ForeignKey('strain.id')))


# TODO: Test
# TODO: Clean up these var names eventually. They are ravioli.
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(100), nullable=False)

    tried = db.relationship('Strain', secondary=tried, backref=db.backref('tried_by', lazy='dynamic'), lazy='dynamic')

    def has_tried(self, strain):
        return self.tried.filter(tried.c.strain_id == strain.id).count() > 0

    def has_not_tried(self):
        return Strain.query.filter(~self.tried.exists())

    def try_strain(self, strain):
        if not self.has_tried(strain):
            self.tried.append(strain)

    def untry_strain(self, strain):
        if self.has_tried(strain):
            self.tried.remove(strain)

    def hash_password(self, password):
        self.password_hash = pwd_context.hash(password)

    def verify_password(self, password):
        return pwd_context.verify(password, self.password_hash)

    def __repr__(self):
        return f'<User {self.username}>'


# TODO: Test
class Strain(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    index = db.Column(db.String(25), index=True, unique=True)
    name = db.Column(db.String(50))
    leafly = db.Column(db.String(50), unique=True)
    species = db.Column(db.String(8))
    description = db.Column(db.String(1000))

    @classmethod
    def initial_query(cls, search_string):
        return db.session.query(cls.name).filter(cls.name.like(search_string + '%'))

    @classmethod
    def follow_up_query(cls, search_string):
        return db.session.query(Strain.name).filter(Strain.name.like('%' + search_string + '%'))

    def avatar(self, size=128):
        digest = md5(self.name.lower().encode()).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'

    @classmethod
    def search(cls, q):
        return cls.query.filter(cls.name.like('%' + q + '%'))

    @classmethod
    def name_to_index(cls, strain_name):
        return db.session.query(cls.index).filter(cls.name == strain_name)

    def __repr__(self):
        return f'<Strain {self.name}>'

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
import logging
from logging.handlers import SMTPHandler


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'], app.config['MAIL_PASSWORD'])
                secure = None
                if app.config['MAIL_USE_TLS']:
                    secure = ()
                mail_handler = SMTPHandler(mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                                           fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                                           toaddrs=app.config['ADMINS'],
                                           subject='Chronicle Failure',
                                           credentials=auth,
                                           secure=secure)
                mail_handler.setLevel(logging.ERROR)
                app.logger.addHandler(mail_handler)
    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db
from app.main import bp
from app.models import Strain
from app import helper
from flask import render_template, redirect, url_for, flash, request, jsonify, current_app
from flask_login import current_user, login_required


# TODO: Test....?
@bp.route('/')
@bp.route('/home')
@login_required
def home():
    return render_template('home.html', title='Home')


# TODO: Test w/ client
# TODO: Also consider adding an actual search button.
# TODO: If add search button, account for empty search.
@bp.route('/strains')
@login_required
def strains_list():
    page = request.args.get('page', 1, type=int)
    filter_ = request.args.get('filter')
    q = request.args.get('q')

    if filter_ == 'tried':
        title = 'Tried Strains'
        strains = current_user.tried.paginate(page, current_app.config['STRAINS_PER_PAGE'], False)
        prev_url, next_url = helper.create_prev_next_urls(strains, filt=filter_)

    elif filter_ == 'not_tried':
        title = 'Not Tried Strains'
        strains = current_user.has_not_tried().paginate(page, current_app.config['STRAINS_PER_PAGE'], False)
        prev_url, next_url = helper.create_prev_next_urls(strains, filt=filter_)

    elif filter_ == 'search':
        if q:
            title = 'Search: ' + q
            strains = Strain.search(q).paginate(page, current_app.config['STRAINS_PER_PAGE'], False)
            prev_url, next_url = helper.create_prev_next_urls(strains, filt=filter_, q=q)
        else:
            return redirect(url_for('main.strains_list'))

    else:
        title = 'Strains'
        strains = Strain.query.paginate(page, current_app.config['STRAINS_PER_PAGE'], False)
        prev_url, next_url = helper.create_prev_next_urls(strains)

    return render_template('strains_list.html', title=title, strains_list=strains.items, next_url=next_url,
                           prev_url=prev_url)


# TODO: test w/ client
@bp.route('/strains/<strain_index>')
@login_required
def some_strain(strain_index):
    strain = Strain.query.filter_by(index=strain_index).first_or_404()
    action = request.args.get('action')

    if action:
        if action == 'try':
            current_user.try_strain(strain)
            flash(f'Strain: {strain.name} has been tried')

        if action == 'untry':
            current_user.untry_strain(strain)
            flash(f'Strain: {strain.name} has been un...tried')

        db.session.commit()

        return redirect(url_for('main.some_strain', strain_index=strain_index))

    else:
        return render_template('strain.html', title=strain.name, strain=strain)


# TODO: test w/ client
@bp.route('/typeahead')
def typeahead():
    search_string = request.args.get('q')
    initial_query = Strain.initial_query(search_string)
    results_count = initial_query.count()
    return jsonify(helper.get_search_results(count=results_count, initial=initial_query, per_page=current_app.config['SEARCH_RESULTS'], search_string=search_string))


# TODO: test w/ client
@bp.route('/name_to_index')
def name_to_index():
    strain_name = request.args.get("name")
    strain_index = Strain.name_to_index(strain_name).first_or_404()
    return redirect(url_for('main.some_strain', strain_index=strain_index[0]))

app/templates/_strain_tile.html
<div>
    <table>
        <tr>
            <td><img src="{{ strain.avatar() }}" alt="Strain Identicon"></td>
            <td><h1><a href="{{ url_for('main.some_strain', strain_index=strain.index) }}">{{ strain.name }}</a></h1></td>
            <td>{{ strain.index }}<br>{{ strain.species }}</td>
        </tr>
    </table>
{#    <h1><a href="{{ url_for('main.some_strain', strain_index=strain.index) }}">{{ strain.name }}</a></h1>#}
{#    <a href="{{ url_for('main.some_strain', strain_index=strain.index) }}">{{ strain.name }}</a>#}
{#    <ul>#}
{#        <li>{{ strain.index }}</li>#}
{#        <li>{{ strain.species }}</li>#}
{#    </ul>#}
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title>{{ title }} - Chronicle</title>
    {% else %}
    <title>Welcome to Chronicle</title>
    {% endif %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.0/typeahead.bundle.js"></script>
    <script defer src="{{ url_for('static', filename='search.js') }}"></script>
</head>
<body>
    <div>
        Chronicle:
        <a href="{{ url_for('main.home') }}">Home</a>
        <a href="{{ url_for('main.strains_list') }}">Strains</a>
        {% if current_user.is_anonymous %}
            <a href="{{ url_for('auth.login') }}">Login</a>
        {% else %}
            <a href="{{ url_for('main.strains_list', filter='tried') }}">Tried</a>
            <a href="{{ url_for('main.strains_list', filter='not_tried') }}">Not Tried</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
            <label for="my_search">Search Strains:</label>
            <input type="text" id="my_search" name="search" autocomplete="off" />
        {% endif %}
    </div>
    <hr>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block content %}
    <h1>Hello, {{ current_user.username }}!</h1>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
{#            {% for error in form.password.errors %}#}
{#            <span style="color: red">[{{ error }}]</span>#}
{#            {% endfor %}#}
        </p>
        <p>
            {{ form.remember }} {{ form.remember.label }}
        </p>
        <p>
            {{ form.submit }}
        </p>
    </form>
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
{% endblock %}

app/templates/strain.html
{% extends 'base.html' %}

{% block content %}
    {% if strain in current_user.tried %}
        <h1>{{ strain.name }} - (Tried)</h1>
    {% else %}
        <h1>{{ strain.name }}</h1>
    {% endif %}
    <ul>
        <li>{{ strain.id }}</li>
        <li>{{ strain.index }}</li>
        <li>{{ strain.leafly }}</li>
        <li>{{ strain.species }}</li>
        <li>{{ strain.description }}</li>
    </ul>
    <hr>
    {% if current_user.has_tried(strain) %}
    <a href="{{ url_for('main.some_strain', strain_index=strain.index, action='untry') }}">Un-Try</a>
    {% else %}
    <a href="{{ url_for('main.some_strain', strain_index=strain.index, action='try') }}">Try</a>
    {% endif %}
{% endblock %}

app/templates/strains_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Strains</h1>
    <hr>
    {% if strains_list %}
        {% for strain in strains_list %}
            {% include '_strain_tile.html' %}
        {% endfor %}
    {% else %}
        <h1>There don't seem to be any strains here!</h1>
    {% endif %}
    {% if prev_url %}
        <a href="{{ prev_url }}">Prev</a>
    {% endif %}
    {% if next_url %}
        <a href="{{ next_url }}">Next</a>
    {% endif %}

{% endblock %}